### ISSUE TITLE
GitHub Action Marketplace version not Updating

### ISSUE THREAD

**Issue by jw-maynard** [reviewdog/action-tfsec#43]
@haya14busa I've noticed that this action, action-tflint, and action-ansiblelint were all listed as versions behind on the Marketplace. I was able to update tflint and ansiblelint by editing the release in the repo and unchecking and then checking `Publish this Action to the GitHub Marketplace` and updating the release. I'm not familiar enough with the Marketplace to know if this is a problem and how to fix it.

**Comment by shogo82148** [comment]
This problem exists not only for tfsec, but also for all actions on the reviewdog org.
Because the actions are based on https://github.com/reviewdog/action-template, and action-template has same problem.

please report to https://github.com/reviewdog/action-template/issues/11 if you have any information.
it helps that we resolve problems of the actions the reviewdog org.
